apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.11.2
    chart: ingress-nginx
    helm:
      valuesObject:
        serviceAccount:
          automountServiceAccountToken: true
        controller:
          allowSnippetAnnotations: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true

