apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awesomeservice
  namespace: argocd
  labels:
    portService: my-awesome-ms
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy
    repoURL: https://github.com/my-silly-organisation/my-awesome-ms
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
